name: tyto
description: A dead simple benchmarking library for Dart and Flutter.
version: 0.0.2
repository: https://github.com/avesbox/tyto

environment:
  sdk: '>=3.9.0 <4.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
dependencies:
  logging: ^1.3.0
  system_info2: ^4.1.0
